name: Typescript Build

on:
  push:
    branches: ["*"]
    paths-ignore: ['**.md']
  pull_request:
    branches: ["*"]

jobs:
  ts_build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-ts')"
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install
      - name: TypeScript Build Test
        run: yarn run build:test